# Generated by Django 6.1.1 on 2026-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(unique=True)),
                ('full_name', models.CharField()),
            ],
            options={
                'unique_together': {('chat_id', 'username')},
            },
        ),
    ]
